# Generated by Django 5.0.3 on 2024-03-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pto_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pto_type', models.CharField(max_length=3, verbose_name='PTO used')),
                ('date_requested', models.DateTimeField(verbose_name='Date requested')),
                ('hours_used', models.CharField(max_length=3, verbose_name='Hours used')),
                ('notes', models.CharField(blank=True, max_length=120, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='pto_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3, verbose_name='Type')),
            ],
        ),
    ]
