# Generated by Django 5.0.3 on 2024-03-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pto_type',
            old_name='type',
            new_name='pto_type',
        ),
        migrations.AlterField(
            model_name='pto_request',
            name='pto_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.pto_type'),
        ),
    ]
