# Generated by Django 5.0.3 on 2024-03-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_type_pto_type_pto_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pto_request',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
