# Generated by Django 5.0.3 on 2024-03-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_pto_request_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='pto_request',
            name='to',
            field=models.CharField(default='VAC', max_length=3, verbose_name='to'),
        ),
    ]
