# Generated by Django 5.0.3 on 2024-03-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_pto_request_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pto_request',
            name='to',
            field=models.CharField(default='', max_length=3, verbose_name='What are you using'),
        ),
    ]
