# Generated by Django 5.0.3 on 2024-03-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_remove_pto_request_to_pto_request_pto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pto_request',
            name='date_requested',
            field=models.CharField(max_length=120, verbose_name='For what dates (MM/DD/YY): '),
        ),
        migrations.AlterField(
            model_name='pto_request',
            name='notes',
            field=models.CharField(blank=True, max_length=120, verbose_name='Notes'),
        ),
    ]
