# Generated by Django 5.0.4 on 2024-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_alter_pto_request_date_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pto_request',
            name='was_sent',
            field=models.CharField(default=1, max_length=8, verbose_name='This request was sent on: '),
            preserve_default=False,
        ),
    ]
