# Generated by Django 5.0.4 on 2024-04-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_alter_pto_request_was_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pto_request',
            name='was_sent',
            field=models.CharField(max_length=8, null=True, verbose_name='This request was sent on: '),
        ),
    ]
